name: Trigger Benchmark
on:
  push:
    branches: [ master ]

jobs:  
  BenchmarkTrigger:
    runs-on: ubuntu-latest
    steps:                      
    - name: 'Checkout recursive' 
      uses: actions/checkout@v2
      with:        
        submodules: recursive                
   
    - name: 'CMake Build'
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        configure-options: -DFASTNOISE2_NOISETOOL=OFF -DFASTNOISE2_TESTS=ON -DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_FLAGS=-m64
    
    - name: 'Upload artifact'
      uses: actions/upload-artifact@v2
      with:
        name: Linux64-BenchmarkBin
        path: ${{ runner.workspace }}/build/tests/FastNoiseBenchmark
        if-no-files-found: error
        
    - id: message-format-1
      uses: ashley-taylor/regex-property-action@1.2
      with:
        value: ${{ github.event.head_commit.message }}
        regex: "^\\s*|[^a-zA-Z0-9_&\\(\\) -]"
        replacement: ""

    - id: message-format
      uses: ashley-taylor/regex-property-action@1.2
      with:
        value: ${{ steps.message-format-1.outputs.value }}
        regex: "(?<=.{50}).*"
        replacement: ""
        
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: Auburn/FastNoise2Benchmarking
        event-type: benchmark
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "msg": "${{ steps.message-format.outputs.value }}"}'
